### ISSUE TITLE
【Auth】需求

### ISSUE THREAD

**Issue by czy88840616** [KF-kissyForm/butterfly#20]
- 分组校验
- ajax异步校验
- 单独关闭某一表单的校验

**Comment by czy88840616** [comment]
伪属性精简化和分离

required-msg="用户名为必填！" required-success-msg="填写正确！" required-success-msg非必须

**Comment by minghe** [comment]
嘿嘿，属性配置优化，因为butterfly要用，我已经搞掉了。

**Comment by czy88840616** [comment]
记得做兼容。。

2012/9/17 明河 notifications@github.com

**Comment by minghe** [comment]
好，我会测下，1.3的auth还没发
