### ISSUE TITLE
随机加载theme.js，返回404

### ISSUE THREAD

**Issue by liuyunclouder** [KF-kissyForm/butterfly#58]
http://a.tbcdn.cn/s/kissy/gallery/uploader/1.4/theme.js?t=20130217192945
有时会去加载theme.js，服务器返回404

![Image](https://f.cloud.github.com/assets/1249065/302322/ca26033a-9602-11e2-9938-d3704ae88efc.png)

不过不影响功能

**Comment by minghe** [comment]
多谢反馈，可以再试下
