### ISSUE TITLE
input.file-input上的中文在IE下乱码

### ISSUE THREAD

**Issue by liuyunclouder** [KF-kissyForm/butterfly#65]
![Alt text](http://dl.dropbox.com/u/21866613/3444.jpg)

**Comment by minghe** [comment]
我在IE下并没有出现这个问题。IE几。页面编码是什么

**Comment by liuyunclouder** [comment]
6 7都有，页面编码为gbk

发自我的 iPad

在 2013-4-4，12:33，明河 notifications@github.com 写道：

**Comment by liuyunclouder** [comment]
只有在切换模式的时候，比如从IE8切换至IE7时才会出现，首次启动浏览器是不会乱码的，这个issue无视吧
